export enum AttributeTypes{
  STRENGTH = "FORÇA",
  DEXTERITY = "DESTREZA",
  POWER = "PODER",
  CONSTITUTION = "CONSTITUIÇÃO",
  APPEARANCE = "APARÊNCIA",
  EDUCATION = "EDUCAÇÃO",
  SIZE = "TAMANHO",
  MOVEMENT = "MOVIMENTO",
  BODY = "CORPO"
}