import {AttributeTypes} from "./Attributes"
import {ExpertiseTypes} from "./Expertises"

export const attributesBaseValues = {
  [AttributeTypes.STRENGTH] : 9,
  [AttributeTypes.DEXTERITY] : 9,
  [AttributeTypes.POWER] : 9,
  [AttributeTypes.CONSTITUTION] : 9,
  [AttributeTypes.APPEARANCE] : 9,
  [AttributeTypes.EDUCATION] : 9,
  [AttributeTypes.SIZE] : 4,
  [AttributeTypes.MOVEMENT] : 4,
  [AttributeTypes.BODY] : 0,

  [ExpertiseTypes.SMALL_GUNFIRE] : 1,
  [ExpertiseTypes.MEDIUM_GUNFIRE] : 1,
  [ExpertiseTypes.HEAVY_GUNFIRE] : 1,
  [ExpertiseTypes.MECHANICAL_RANGED_WEAPON] : 1,
  [ExpertiseTypes.THROW] : 3,
  [ExpertiseTypes.DODGE] : 9,
  [ExpertiseTypes.FIGHT_BRAWL] : 1,
  [ExpertiseTypes.FIGHT_WEAPONS] : 1,
  [ExpertiseTypes.FIND_HIDDEN] : 1,
  [ExpertiseTypes.LOCKPICKING] : 1,
  [ExpertiseTypes.BARGAIN] : 1,
  [ExpertiseTypes.DISGUISE] : 1,
  [ExpertiseTypes.FIND] : 3,
  [ExpertiseTypes.CLIMB] : 3,
  [ExpertiseTypes.HIDE] : 3,
  [ExpertiseTypes.PHOTO] : 3,
  [ExpertiseTypes.STEALTH] : 2,
  [ExpertiseTypes.NATIVE_LANGUAGE] : 9,
  [ExpertiseTypes.OTHERS_LANGUAGE] : 1,
  [ExpertiseTypes.SWIMMING] : 3,
  [ExpertiseTypes.JUMP] : 3,
  [ExpertiseTypes.LUCK] : 1,
  [ExpertiseTypes.TRACK] : 1,
  [ExpertiseTypes.RECOGNIZE_PATTERNS] : 2,
  [ExpertiseTypes.SURVIVAL] : 1,
  [ExpertiseTypes.USE_LIBRARIES] : 2,
  [ExpertiseTypes.USE_COMPUTERS] : 1,

  [ExpertiseTypes.CHARM] : 9,
  [ExpertiseTypes.SMALL_TALK] : 1,
  [ExpertiseTypes.INTIMIDATION] : 1,
  [ExpertiseTypes.PERSUADE] : 1,

  [ExpertiseTypes.HORSE_RIDING] : 1,
  [ExpertiseTypes.DRIVE_AUTO] : 1,
  [ExpertiseTypes.NAVIGATION] : 1,
  [ExpertiseTypes.OPERATE_MACH] : 1,
  [ExpertiseTypes.ORIENTATION] : 1,
  [ExpertiseTypes.PILOT] : 1,

  [ExpertiseTypes.MEDICINE] : 1,
  [ExpertiseTypes.FIRST_AID] : 5,
  [ExpertiseTypes.PSICOLOGY] : 1,

  [ExpertiseTypes.ARCHEOLOGY] : 1,
  [ExpertiseTypes.SCIENCE] :  2,
  [ExpertiseTypes.KNOWLEDGE] : 9,
  [ExpertiseTypes.ELETRICIAN] : 1,
  [ExpertiseTypes.PHYSICS] : 1,
  [ExpertiseTypes.MECHANICAL] : 1,
  [ExpertiseTypes.CONTABILITY] : 1,
  [ExpertiseTypes.LAW] : 2,
  [ExpertiseTypes.DRAMA] : 1,
  [ExpertiseTypes.GEOGRAPHY] : 1,
  [ExpertiseTypes.HISTORY] : 1,
  [ExpertiseTypes.INVESTIGATION] : 1,
  [ExpertiseTypes.INFORMATION_THEORY] : 1,
  [ExpertiseTypes.OTHER_SIDE_EXPOSURE] : 0,
}


export const attributesNames = {
  [AttributeTypes.STRENGTH] : "Força",
  [AttributeTypes.DEXTERITY] : "Destreza",
  [AttributeTypes.POWER] : "Poder",
  [AttributeTypes.CONSTITUTION] : "Constituição",
  [AttributeTypes.APPEARANCE] : "Aparência",
  [AttributeTypes.EDUCATION] : "Educação",
  [AttributeTypes.SIZE] : "Tamanho",
  [AttributeTypes.MOVEMENT] : "Movimento",
  [AttributeTypes.BODY] : "Corpo",

  [ExpertiseTypes.SMALL_GUNFIRE] : "Armas leves",
  [ExpertiseTypes.MEDIUM_GUNFIRE] : "Armas médias",
  [ExpertiseTypes.HEAVY_GUNFIRE] : "Armas pesadas",
  [ExpertiseTypes.MECHANICAL_RANGED_WEAPON] : "Armas mecânicas",
  [ExpertiseTypes.THROW] : "Lançar",
  [ExpertiseTypes.DODGE] : "Esquivar",
  [ExpertiseTypes.FIGHT_BRAWL] : "Lutar (Briga)",
  [ExpertiseTypes.FIGHT_WEAPONS] : "Lutar (Armas)",
  [ExpertiseTypes.FIND_HIDDEN] : "Achar escondido",
  [ExpertiseTypes.LOCKPICKING] : "Arrombar",
  [ExpertiseTypes.BARGAIN] : "Barganhar",
  [ExpertiseTypes.DISGUISE] : "Disfarce",
  [ExpertiseTypes.FIND] : "Encontrar",
  [ExpertiseTypes.CLIMB] : "Escalar",
  [ExpertiseTypes.HIDE] : "Esconder (Objetos)",
  [ExpertiseTypes.PHOTO] : "Fotografia",
  [ExpertiseTypes.STEALTH] : "Furtividade",
  [ExpertiseTypes.NATIVE_LANGUAGE] : "Lingua (Nativa)",
  [ExpertiseTypes.OTHERS_LANGUAGE] : "Lingua (Estrang.)",
  [ExpertiseTypes.SWIMMING] : "Nadar",
  [ExpertiseTypes.JUMP] : "Pular",
  [ExpertiseTypes.LUCK] : "Sorte",
  [ExpertiseTypes.TRACK] : "Rastrear",
  [ExpertiseTypes.RECOGNIZE_PATTERNS] : "Encontrar padrões",
  [ExpertiseTypes.SURVIVAL] : "Sobrevivência",
  [ExpertiseTypes.USE_LIBRARIES] : "Usar bibliotecas",
  [ExpertiseTypes.USE_COMPUTERS] : "Usar computadores",

  [ExpertiseTypes.CHARM] : "Charme",
  [ExpertiseTypes.SMALL_TALK] : "Lábia",
  [ExpertiseTypes.INTIMIDATION] : "Intimidação",
  [ExpertiseTypes.PERSUADE] : "Persuasão",

  [ExpertiseTypes.HORSE_RIDING] : "Cavalgar",
  [ExpertiseTypes.DRIVE_AUTO] : "Dirigir auto.",
  [ExpertiseTypes.NAVIGATION] : "Navegação",
  [ExpertiseTypes.OPERATE_MACH] : "Operar Maquinário",
  [ExpertiseTypes.ORIENTATION] : "Orientação",
  [ExpertiseTypes.PILOT] : "Pilotar",

  [ExpertiseTypes.MEDICINE] : "Medicina",
  [ExpertiseTypes.FIRST_AID] : "Primeiros Socorros",
  [ExpertiseTypes.PSICOLOGY] : "Psicologia",

  [ExpertiseTypes.ARCHEOLOGY] : "Arqueologia",
  [ExpertiseTypes.SCIENCE] :  "Ciência",
  [ExpertiseTypes.KNOWLEDGE] : "Conhecimento",
  [ExpertiseTypes.ELETRICIAN] : "Elétrica",
  [ExpertiseTypes.PHYSICS] : "Física",
  [ExpertiseTypes.MECHANICAL] : "Mecânicas",
  [ExpertiseTypes.CONTABILITY] : "Finanças",
  [ExpertiseTypes.LAW] : "Direito",
  [ExpertiseTypes.DRAMA] : "Drama",
  [ExpertiseTypes.GEOGRAPHY] : "Geografia",
  [ExpertiseTypes.HISTORY] : "História",
  [ExpertiseTypes.INVESTIGATION] : "Investigação",
  [ExpertiseTypes.INFORMATION_THEORY] : "T.I",

  [ExpertiseTypes.OTHER_SIDE_EXPOSURE] : "Exposição",
}

export const attributesHighestValues = {
  [AttributeTypes.STRENGTH] : 20,
  [AttributeTypes.DEXTERITY] : 20,
  [AttributeTypes.POWER] : 20,
  [AttributeTypes.CONSTITUTION] : 20,
  [AttributeTypes.APPEARANCE] : 20,
  [AttributeTypes.EDUCATION] : 20,
  [AttributeTypes.SIZE] : 10,
  [AttributeTypes.MOVEMENT] : 10,
  [AttributeTypes.BODY] : 1,

  [ExpertiseTypes.SMALL_GUNFIRE] : 20,
  [ExpertiseTypes.MEDIUM_GUNFIRE] : 20,
  [ExpertiseTypes.HEAVY_GUNFIRE] : 20,
  [ExpertiseTypes.MECHANICAL_RANGED_WEAPON] : 20,
  [ExpertiseTypes.THROW] : 20,
  [ExpertiseTypes.DODGE] : 20,
  [ExpertiseTypes.FIGHT_BRAWL] : 20,
  [ExpertiseTypes.FIGHT_WEAPONS] : 20,
  [ExpertiseTypes.FIND_HIDDEN] : 20,
  [ExpertiseTypes.LOCKPICKING] : 20,
  [ExpertiseTypes.BARGAIN] : 20,
  [ExpertiseTypes.DISGUISE] : 20,
  [ExpertiseTypes.FIND] : 20,
  [ExpertiseTypes.CLIMB] : 20,
  [ExpertiseTypes.HIDE] : 20,
  [ExpertiseTypes.PHOTO] :20,
  [ExpertiseTypes.STEALTH] :20,
  [ExpertiseTypes.NATIVE_LANGUAGE] :20,
  [ExpertiseTypes.OTHERS_LANGUAGE] :20,
  [ExpertiseTypes.SWIMMING] :20,
  [ExpertiseTypes.JUMP] :20,
  [ExpertiseTypes.LUCK] :20,
  [ExpertiseTypes.TRACK] :20,
  [ExpertiseTypes.RECOGNIZE_PATTERNS] :20,
  [ExpertiseTypes.SURVIVAL] :20,
  [ExpertiseTypes.USE_LIBRARIES] :20,
  [ExpertiseTypes.USE_COMPUTERS] :20,
  [ExpertiseTypes.CHARM] :20,
  [ExpertiseTypes.SMALL_TALK] :20,
  [ExpertiseTypes.INTIMIDATION] :20,
  [ExpertiseTypes.PERSUADE] :20,
  [ExpertiseTypes.HORSE_RIDING] :20,
  [ExpertiseTypes.DRIVE_AUTO] :20,
  [ExpertiseTypes.NAVIGATION] :20,
  [ExpertiseTypes.OPERATE_MACH] :20,
  [ExpertiseTypes.ORIENTATION] :20,
  [ExpertiseTypes.PILOT] :20,
  [ExpertiseTypes.MEDICINE] :20,
  [ExpertiseTypes.FIRST_AID] :20,
  [ExpertiseTypes.PSICOLOGY] :20,
  [ExpertiseTypes.ARCHEOLOGY] :20,
  [ExpertiseTypes.SCIENCE] : 20,
  [ExpertiseTypes.KNOWLEDGE] :20,
  [ExpertiseTypes.ELETRICIAN] :20,
  [ExpertiseTypes.PHYSICS] :20,
  [ExpertiseTypes.MECHANICAL] :20,
  [ExpertiseTypes.CONTABILITY] :20,
  [ExpertiseTypes.LAW] :20,
  [ExpertiseTypes.DRAMA] :20,
  [ExpertiseTypes.GEOGRAPHY] :20,
  [ExpertiseTypes.HISTORY] :20,
  [ExpertiseTypes.INVESTIGATION] :20,
  [ExpertiseTypes.INFORMATION_THEORY] :20,
  [ExpertiseTypes.OTHER_SIDE_EXPOSURE] : 100,
}

export const attributesPlayerHighestValues = {
  [AttributeTypes.STRENGTH] : 16,
  [AttributeTypes.DEXTERITY] : 16,
  [AttributeTypes.POWER] : 16,
  [AttributeTypes.CONSTITUTION] : 16,
  [AttributeTypes.APPEARANCE] : 16,
  [AttributeTypes.EDUCATION] : 16,
  [AttributeTypes.SIZE] : 10,
  [AttributeTypes.MOVEMENT] : 10,
  [AttributeTypes.BODY] : 1,

  [ExpertiseTypes.SMALL_GUNFIRE] : 16,
  [ExpertiseTypes.MEDIUM_GUNFIRE] : 16,
  [ExpertiseTypes.HEAVY_GUNFIRE] : 16,
  [ExpertiseTypes.MECHANICAL_RANGED_WEAPON] : 16,
  [ExpertiseTypes.THROW] : 16,
  [ExpertiseTypes.DODGE] : 16,
  [ExpertiseTypes.FIGHT_BRAWL] : 16,
  [ExpertiseTypes.FIGHT_WEAPONS] : 16,
  [ExpertiseTypes.FIND_HIDDEN] : 16,
  [ExpertiseTypes.LOCKPICKING] : 16,
  [ExpertiseTypes.BARGAIN] : 16,
  [ExpertiseTypes.DISGUISE] : 16,
  [ExpertiseTypes.FIND] : 16,
  [ExpertiseTypes.CLIMB] : 16,
  [ExpertiseTypes.HIDE] : 16,
  [ExpertiseTypes.PHOTO] : 16,
  [ExpertiseTypes.STEALTH] :16,
  [ExpertiseTypes.NATIVE_LANGUAGE] :16,
  [ExpertiseTypes.OTHERS_LANGUAGE] :16,
  [ExpertiseTypes.SWIMMING] :16,
  [ExpertiseTypes.JUMP] :16,
  [ExpertiseTypes.LUCK] :16,
  [ExpertiseTypes.TRACK] :16,
  [ExpertiseTypes.RECOGNIZE_PATTERNS] :16,
  [ExpertiseTypes.SURVIVAL] :16,
  [ExpertiseTypes.USE_LIBRARIES] :16,
  [ExpertiseTypes.USE_COMPUTERS] :16,
  [ExpertiseTypes.CHARM] :16,
  [ExpertiseTypes.SMALL_TALK] :16,
  [ExpertiseTypes.INTIMIDATION] :16,
  [ExpertiseTypes.PERSUADE] :16,
  [ExpertiseTypes.HORSE_RIDING] :16,
  [ExpertiseTypes.DRIVE_AUTO] :16,
  [ExpertiseTypes.NAVIGATION] :16,
  [ExpertiseTypes.OPERATE_MACH] :16,
  [ExpertiseTypes.ORIENTATION] :16,
  [ExpertiseTypes.PILOT] :16,
  [ExpertiseTypes.MEDICINE] :16,
  [ExpertiseTypes.FIRST_AID] :16,
  [ExpertiseTypes.PSICOLOGY] :16,
  [ExpertiseTypes.ARCHEOLOGY] :16,
  [ExpertiseTypes.SCIENCE] : 16,
  [ExpertiseTypes.KNOWLEDGE] :16,
  [ExpertiseTypes.ELETRICIAN] :16,
  [ExpertiseTypes.PHYSICS] :16,
  [ExpertiseTypes.MECHANICAL] :16,
  [ExpertiseTypes.CONTABILITY] :16,
  [ExpertiseTypes.LAW] :16,
  [ExpertiseTypes.DRAMA] :16,
  [ExpertiseTypes.GEOGRAPHY] :16,
  [ExpertiseTypes.HISTORY] :16,
  [ExpertiseTypes.INVESTIGATION] :16,
  [ExpertiseTypes.INFORMATION_THEORY] :16,
  [ExpertiseTypes.OTHER_SIDE_EXPOSURE] : 100,
}