import {AttributeTypes} from "./Attributes"
import {ExpertiseTypes} from "./Expertises"

export const attributesBaseValues = {
  [AttributeTypes.STRENGTH] : 9,
  [AttributeTypes.DEXTERITY] : 9,
  [AttributeTypes.POWER] : 9,
  [AttributeTypes.CONSTITUTION] : 9,
  [AttributeTypes.APPEARANCE] : 9,
  [AttributeTypes.EDUCATION] : 9,
  [AttributeTypes.SIZE] : 4,
  [AttributeTypes.MOVEMENT] : 4,

  [ExpertiseTypes.SMALL_GUNFIRE] : 1,
  [ExpertiseTypes.MEDIUM_GUNFIRE] : 1,
  [ExpertiseTypes.HEAVY_GUNFIRE] : 1,
  [ExpertiseTypes.MECHANICAL_RANGED_WEAPON] : 1,
  [ExpertiseTypes.THROW] : 3,
  [ExpertiseTypes.DODGE] : 9,
  [ExpertiseTypes.FIGHT_BRAWL] : 1,
  [ExpertiseTypes.FIGHT_WEAPONS] : 1,
  [ExpertiseTypes.FIND_HIDDEN] : 1,
  [ExpertiseTypes.LOCKPICKING] : 1,
  [ExpertiseTypes.BARGAIN] : 1,
  [ExpertiseTypes.DISGUISE] : 1,
  [ExpertiseTypes.FIND] : 3,
  [ExpertiseTypes.CLIMB] : 3,
  [ExpertiseTypes.HIDE] : 3,
  [ExpertiseTypes.PHOTO] : 3,
  [ExpertiseTypes.STEALTH] : 2,
  [ExpertiseTypes.NATIVE_LANGUAGE] : 9,
  [ExpertiseTypes.OTHERS_LANGUAGE] : 1,
  [ExpertiseTypes.SWIMMING] : 3,
  [ExpertiseTypes.JUMP] : 3,
  [ExpertiseTypes.LUCK] : 1,
  [ExpertiseTypes.TRACK] : 1,
  [ExpertiseTypes.RECOGNIZE_PATTERNS] : 2,
  [ExpertiseTypes.SURVIVAL] : 1,
  [ExpertiseTypes.USE_LIBRARIES] : 2,
  [ExpertiseTypes.USE_COMPUTERS] : 1,

  [ExpertiseTypes.CHARM] : 9,
  [ExpertiseTypes.SMALL_TALK] : 1,
  [ExpertiseTypes.INTIMIDATION] : 1,
  [ExpertiseTypes.PERSUADE] : 1,

  [ExpertiseTypes.HORSE_RIDING] : 1,
  [ExpertiseTypes.DRIVE_AUTO] : 1,
  [ExpertiseTypes.NAVIGATION] : 1,
  [ExpertiseTypes.OPERATE_MACH] : 1,
  [ExpertiseTypes.ORIENTATION] : 1,
  [ExpertiseTypes.PILOT] : 1,

  [ExpertiseTypes.MEDICINE] : 1,
  [ExpertiseTypes.FIRST_AID] : 5,
  [ExpertiseTypes.PSICOLOGY] : 1,

  [ExpertiseTypes.ARCHEOLOGY] : 1,
  [ExpertiseTypes.SCIENCE] :  2,
  [ExpertiseTypes.KNOWLEDGE] : 9,
  [ExpertiseTypes.ELETRICIAN] : 1,
  [ExpertiseTypes.PHYSICS] : 1,
  [ExpertiseTypes.MECHANICAL] : 1,
  [ExpertiseTypes.CONTABILITY] : 1,
  [ExpertiseTypes.LAW] : 2,
  [ExpertiseTypes.DRAMA] : 1,
  [ExpertiseTypes.GEOGRAPHY] : 1,
  [ExpertiseTypes.HISTORY] : 1,
  [ExpertiseTypes.INVESTIGATION] : 1,
  [ExpertiseTypes.INFORMATION_THEORY] : 1,
  [ExpertiseTypes.OTHER_SIDE_EXPOSURE] : 1,
}



export const attributesHighestValues = {
  [AttributeTypes.STRENGTH] : 9,
  [AttributeTypes.DEXTERITY] : 9,
  [AttributeTypes.POWER] : 9,
  [AttributeTypes.CONSTITUTION] : 9,
  [AttributeTypes.APPEARANCE] : 9,
  [AttributeTypes.EDUCATION] : 9,
  [AttributeTypes.SIZE] : 4,
  [AttributeTypes.MOVEMENT] : 4,

  [ExpertiseTypes.SMALL_GUNFIRE] : 1,
  [ExpertiseTypes.MEDIUM_GUNFIRE] : 1,
  [ExpertiseTypes.HEAVY_GUNFIRE] : 1,
  [ExpertiseTypes.MECHANICAL_RANGED_WEAPON] : 1,
  [ExpertiseTypes.THROW] : 3,
  [ExpertiseTypes.DODGE] : 9,
  [ExpertiseTypes.FIGHT_BRAWL] : 1,
  [ExpertiseTypes.FIGHT_WEAPONS] : 1,
  [ExpertiseTypes.FIND_HIDDEN] : 1,
  [ExpertiseTypes.LOCKPICKING] : 1,
  [ExpertiseTypes.BARGAIN] : 1,
  [ExpertiseTypes.DISGUISE] : 1,
  [ExpertiseTypes.FIND] : 3,
  [ExpertiseTypes.CLIMB] : 3,
  [ExpertiseTypes.HIDE] : 3,
  [ExpertiseTypes.PHOTO] : 3,
  [ExpertiseTypes.STEALTH] : 2,
  [ExpertiseTypes.NATIVE_LANGUAGE] : 9,
  [ExpertiseTypes.OTHERS_LANGUAGE] : 1,
  [ExpertiseTypes.SWIMMING] : 3,
  [ExpertiseTypes.JUMP] : 3,
  [ExpertiseTypes.LUCK] : 1,
  [ExpertiseTypes.TRACK] : 1,
  [ExpertiseTypes.RECOGNIZE_PATTERNS] : 2,
  [ExpertiseTypes.SURVIVAL] : 1,
  [ExpertiseTypes.USE_LIBRARIES] : 2,
  [ExpertiseTypes.USE_COMPUTERS] : 1,

  [ExpertiseTypes.CHARM] : 9,
  [ExpertiseTypes.SMALL_TALK] : 1,
  [ExpertiseTypes.INTIMIDATION] : 1,
  [ExpertiseTypes.PERSUADE] : 1,

  [ExpertiseTypes.HORSE_RIDING] : 1,
  [ExpertiseTypes.DRIVE_AUTO] : 1,
  [ExpertiseTypes.NAVIGATION] : 1,
  [ExpertiseTypes.OPERATE_MACH] : 1,
  [ExpertiseTypes.ORIENTATION] : 1,
  [ExpertiseTypes.PILOT] : 1,

  [ExpertiseTypes.MEDICINE] : 1,
  [ExpertiseTypes.FIRST_AID] : 5,
  [ExpertiseTypes.PSICOLOGY] : 1,

  [ExpertiseTypes.ARCHEOLOGY] : 1,
  [ExpertiseTypes.SCIENCE] :  2,
  [ExpertiseTypes.KNOWLEDGE] : 9,
  [ExpertiseTypes.ELETRICIAN] : 1,
  [ExpertiseTypes.PHYSICS] : 1,
  [ExpertiseTypes.MECHANICAL] : 1,
  [ExpertiseTypes.CONTABILITY] : 1,
  [ExpertiseTypes.LAW] : 2,
  [ExpertiseTypes.DRAMA] : 1,
  [ExpertiseTypes.GEOGRAPHY] : 1,
  [ExpertiseTypes.HISTORY] : 1,
  [ExpertiseTypes.INVESTIGATION] : 1,
  [ExpertiseTypes.INFORMATION_THEORY] : 1,
  [ExpertiseTypes.OTHER_SIDE_EXPOSURE] : 1,
}